# Generated by Google Workspace MCP
# Stage 1: Build
FROM node:20-slim AS builder

WORKDIR /app

# Install dependencies first for caching
# We use npm install instead of npm ci to allow building even if package-lock.json is missing or out of sync
COPY package.json package-lock.json* ./
RUN npm install

# Copy source code and build
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20-slim

WORKDIR /app

# Create non-root user
RUN useradd --create-home --shell /bin/bash app

# Install only production dependencies
COPY package.json package-lock.json* ./
RUN npm install --omit=dev

# Copy built artifacts from builder
COPY --from=builder /app/dist ./dist

# Set up metadata and permissions
RUN mkdir -p /app/store_creds \
    && chown -R app:app /app \
    && chmod 755 /app/store_creds

# Default environment variables
ENV NODE_ENV=production
ENV PORT=3000

USER app

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD node -e "fetch('http://localhost:' + process.env.PORT + '/api/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"

# Start server
CMD ["node", "dist/server.js"]
